
version: 2

models:
  - name: mile1part1
    description: "Monthly average for different attributes"
    columns:
      - name: code
        description: "Code of each scheme"
        tests:
          - unique
          - not_null
  - name: mile1part2_max
    description: "Maximum Nav for each scheme"
    columns:
      - name: code
        description: "Code of each scheme"
        tests:
          - unique
          - not_null
  - name: mile1part2_min
    description: "Minimum Nav for each scheme"
    columns:
      - name: code
        description: "Code of each scheme"
        tests:
          - unique
          - not_null
  - name: mile2part3
    description: "List of mutual funds which were discontinued in a given year"
    columns:
      - name: code
        description: "Code of each scheme"
        tests:
          - unique
          - not_null